### ISSUE TITLE
Inconsistent behaviour between node and browser environments

### ISSUE THREAD

**Issue by jonahlau** [mulesoft-labs/raml-javascript-generator#10]
Hi there, thanks for your work on this awesome library. I'm successfully instantiating the client in the Chrome, but I've noticed two inconsistencies between the generated client in node and browser environments.

## TypeError: client.request is not a function

 try to make a request (e.g. `client.resources.Resource.get()`), I'm getting an error saying `client.request is not a function`.
**
I don't get this error in node however.**

It turns out in the browser, the request property on client is an Object and there is a request method on that object (which is the method needed in this instance).  My temporary solution is to change line 70 of the generated client's `index.js` to:
```
return client.request.request(reqOpts)
```

## When providing headers, the key 'content-type' header is case sensitive in browser

For example, when I call in the **browser**: `client.resources.Resource.post({ foo: bar }, {headers: { 'Content-Type': 'application/x-www-form-urlencoded' }})`, my `Content-Type` header doesn't get sent and I get an error from my server.  However, using `content-type` (lowercase) sends the correct header. 

However, both uppercase/lowercase works fine in **node**.

**Comment by blakeembrey** [comment]
@jonahlau It sounds like you're using two different versions of the request library - one on node and another on the browser. It's pegged at `1.x` (https://github.com/mulesoft-labs/raml-javascript-generator/blob/master/lib/templates/package.json.hbs#L24) which is the correct API, but it sounds like you're using `3.x` in the browser? https://github.com/blakeembrey/popsicle/releases/tag/v3.0.1

On the case-sensitive headers, this is because of how node works. Node will always lower-case headers (https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L353) while browser correctly send headers. If I could work around the node issue I would, because headers are case-insensitive. I'd investigate the server you're using, it's a bug in there.

**Comment by blakeembrey** [comment]
Ok, I just checked and noticed the issue with lowercase/uppercase in node. Node is always sending lower-case headers because of a quirk with the library implementation. I'm going to issue a patch for this into the request library, but be aware **this will make it act like the browser**.

**Comment by jonahlau** [comment]
Thanks @blakeembrey!  I'm going to check out your suggestions for the first issue and post what I find out here.

**Comment by jonahlau** [comment]
Sorry for the delay. So your initial suspicion that I'm using the wrong request library is correct.  npm installing popsicle @1.x removed the inconsistency. Consider this issue resolved.  Thanks for your help!
